    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Regenerate missing Android platform files
        script: flutter create --platforms=android .
      - name: Build APK (release)
        script: flutter build apk --release
